# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.cache/wt [current_project]
set_property parent.project_path D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/sources_1/new/defines.v
  D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/sources_1/new/ctrl.v
  D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/sources_1/new/div.v
  D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/sources_1/new/ex.v
  D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/sources_1/new/ex_mem.v
  D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/sources_1/new/fenping.v
  D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/sources_1/new/hilo_reg.v
  D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/sources_1/new/id.v
  D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/sources_1/new/id_ex.v
  D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/sources_1/new/if_id.v
  D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/sources_1/new/inst_rom.v
  D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/sources_1/new/mem.v
  D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/sources_1/new/mem_wb.v
  D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/sources_1/new/openmips.v
  D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/sources_1/new/openmips_min_sopc.v
  D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/sources_1/new/pc_reg.v
  D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/sources_1/new/regfile.v
  D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/sources_1/new/x7seg.v
  D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/sources_1/new/x7seg_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files D:/作业/计算机体系结构/CPUtest/MIPS32/MIPS32.srcs/constrs_1/new/top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top x7seg_top -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef x7seg_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file x7seg_top_utilization_synth.rpt -pb x7seg_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
